[package]
name = "partial_collider"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "0.9.6"
hex = "0.4.3"
rand = "0.8.4"
num_cpus = "1.13.0"
